#!/usr/bin/env bash

set -ex

black --check --diff app main.py migrations/versions tests
isort --profile black --check-only app main.py migrations/versions tests

mypy app main.py migrations/versions tests
